# Spring Boot configuration
spring:
  profiles:
    active: development
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: DEBUG

# Server configuration
server:
  port: 8080
  sessionTimeout: 30

#PackagesToScan
entityManager:
  packagesToScan: com.kaluzny.domain

# Database
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/book_db?createDatabaseIfNotExist=true
  username: postgres
  password: postgres

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true